### ISSUE TITLE
Can not compile the batch_generator.cpp

### ISSUE THREAD

**Issue by hjpwhu** [malllabiisc/WordGCN#1]
Hi,

The WordGCN is an interesting thing. However, I can't compile the batch_generator.cpp with the command "make" following the Readme. Meanwhile, the requirements can not be found in the repository.

**g++ batch_generator.cpp -o batchGen.so -fPIC -shared -pthread -O3 -march=native -std=c++11	
batch_generator.cpp:96:3: error: expected identifier before ‘)’ token
   ) {
   ^
makefile:2: recipe for target 'all' failed
make: *** [all] Error 1**

Thanks.

**Comment by hjpwhu** [comment]
> Hi,
> 
> The WordGCN is an interesting thing. However, I can't compile the batch_generator.cpp with the command "make" following the Readme on Ubuntu 18.04 Lts. Meanwhile, the requirements can not be found in the repository.
> 
> **g++ batch_generator.cpp -o batchGen.so -fPIC -shared -pthread -O3 -march=native -std=c++11 batch_generator.cpp:96:3: error: expected identifier before ‘)’ token ) { ^ makefile:2: recipe for target 'all' failed make: *** [all] Error 1**
> 
> Thanks.

**Comment by svjan5** [comment]
Hi @hjpwhu,
Thank you for pointing out the error. I have corrected it, please do `git pull` and try once again.

**Comment by hjpwhu** [comment]
> Hi @hjpwhu,
> Thank you for pointing out the error. I have corrected it, please do `git pull` and try once again.

Hi @svjan5,
Thank you for your reply, and the "make" command can work. However, when I run "python syngcn.py -name test_embeddings -gpu 0" in terminal on Ubuntu 18.04 with TensorFlow 1.90, I got the following information, can you do me a favor? Thanks.

**/home/hjp/Workspace/Tempshop/Python/Conda/envs/Env36Tf190/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/hjp/Workspace/Tempshop/Python/Conda/envs/Env36Tf190/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "syngcn.py", line 5, in <module>
    from web.embedding import Embedding
ModuleNotFoundError: No module named 'web'**

**Comment by svjan5** [comment]
Hi,
I am sorry for the trouble. The error was because of a missing package: [word-embeddings-benchmark](https://github.com/kudkudak/word-embeddings-benchmarks). I have included that in the readme.md. Once that is installed I think it should work without any problem. Please let me know if you face any difficulty.

**Comment by hjpwhu** [comment]
**Hi, thank you for your reply. But I find the following information when I run the command "python syngcn.py -name test_embeddings -gpu 0" in terminal:**

(Env36Tf190) hjp@cvnlpserver:~/Downloads/tmp/tmp/tmp/WordGCN$ python syngcn.py -name test_embeddings -gpu 0
2019-06-20 12:49:28,410 - [INFO] - {'gpu': '0', 'name': 'test_embeddings_20_06_2019_12:49:28', 'embed_loc': None, 'embed_dim': 100, 'total_sents': 56974869, 'lr': 0.001, 'batch_size': 512, 'max_epochs': 5, 'l2': 0.0, 'seed': 1234, 'sample': 0.0001, 'num_neg': 25, 'side_int': 10000, 'gcn_layer': 1, 'dropout': 1.0, 'opt': 'adam', 'onlyDump': False, 'context': False, 'restore': False, 'log_db': 'aaai_runs', 'emb_dir': './embeddings/', 'log_dir': './log/', 'config_dir': './config/'}
{'batch_size': 512,
 'config_dir': './config/',
 'context': False,
 'dropout': 1.0,
 'emb_dir': './embeddings/',
 'embed_dim': 100,
 'embed_loc': None,
 'gcn_layer': 1,
 'gpu': '0',
 'l2': 0.0,
 'log_db': 'aaai_runs',
 'log_dir': './log/',
 'lr': 0.001,
 'max_epochs': 5,
 'name': 'test_embeddings_20_06_2019_12:49:28',
 'num_neg': 25,
 'onlyDump': False,
 'opt': 'adam',
 'restore': False,
 'sample': 0.0001,
 'seed': 1234,
 'side_int': 10000,
 'total_sents': 56974869}
2019-06-20 12:49:28,411 - [INFO] - Loading data

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/hjp/Workspace/Tempshop/Python/Conda/envs/Env36Tf190/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/hjp/Workspace/Tempshop/Python/Conda/envs/Env36Tf190/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-06-20 12:49:44.344451: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-20 12:49:44.567206: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x558004bfc1e0 executing computations on platform CUDA. Devices:
2019-06-20 12:49:44.567261: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-06-20 12:49:44.588490: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2197450000 Hz
2019-06-20 12:49:44.590252: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x558004cb8280 executing computations on platform Host. Devices:
2019-06-20 12:49:44.590295: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-20 12:49:44.590885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6325
pciBusID: 0000:02:00.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2019-06-20 12:49:44.590934: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-20 12:49:44.592556: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-20 12:49:44.592586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-20 12:49:44.592600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-20 12:49:44.593108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10468 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
2019-06-20 12:49:49,246 - [INFO] - Epoch: 0
Segmentation fault (core dumped)

**I try to solve the problem, but it still not works. Could you give me some advice？ And the packages in environment as following:**

(Env36Tf190) hjp@cvnlpserver:~/Downloads/tmp/tmp/tmp/WordGCN$ conda list 
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at /home/hjp/Workspace/Tempshop/Python/Conda/envs/Env36Tf190:
#
# Name                    Version                   Build  Channel
absl-py                   0.7.1                    pypi_0    pypi
alabaster                 0.7.12                   py36_0  
anaconda                  2019.03                  py36_0  
anaconda-client           1.7.2                    py36_0  
anaconda-project          0.8.2                    py36_0  
asn1crypto                0.24.0                   py36_0  
astor                     0.7.1                    pypi_0    pypi
astroid                   2.2.5                    py36_0  
astropy                   3.1.2            py36h7b6447c_0  
atomicwrites              1.3.0                    py36_1  
attrs                     19.1.0                   py36_1  
babel                     2.6.0                    py36_0  
backcall                  0.1.0                    py36_0  
backports                 1.0                      py36_1  
backports.os              0.1.1                    py36_0  
backports.shutil_get_terminal_size 1.0.0                    py36_2  
beautifulsoup4            4.7.1                    py36_1  
bitarray                  0.8.3            py36h14c3975_0  
bkcharts                  0.2              py36h735825a_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py36_0  
blosc                     1.15.0               hd408876_0  
bokeh                     1.0.4                    py36_0  
boto                      2.49.0                   py36_0  
bottleneck                1.2.1            py36h035aef0_1  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2019.1.23                     0  
cairo                     1.14.12              h8948797_3  
certifi                   2019.3.9                 py36_0  
cffi                      1.12.2           py36h2e261b9_1  
chardet                   3.0.4                    py36_1  
click                     7.0                      py36_0  
cloudpickle               0.8.0                    py36_0  
clyent                    1.2.2                    py36_1  
colorama                  0.4.1                    py36_0  
contextlib2               0.5.5            py36h6c84a62_0  
cryptography              2.6.1            py36h1ba5d50_0  
curl                      7.64.0               hbc83047_2  
cycler                    0.10.0           py36h93f1223_0  
cython                    0.29.6           py36he6710b0_0  
cytoolz                   0.9.0.1          py36h14c3975_1  
dask                      1.1.4                    py36_1  
dask-core                 1.1.4                    py36_1  
dbus                      1.13.6               h746ee38_0  
decorator                 4.4.0                    py36_1  
defusedxml                0.5.0                    py36_1  
distributed               1.26.0                   py36_1  
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.14             py36hb0f60f5_0  
entrypoints               0.3                      py36_0  
et_xmlfile                1.0.1            py36hd6bccc3_0  
expat                     2.2.6                he6710b0_0  
fastcache                 1.0.2            py36h14c3975_2  
flask                     1.0.2                    py36_1  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
fribidi                   1.0.5                h7b6447c_0  
futures                   3.1.1                    pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
get_terminal_size         1.0.0                haa9412d_0  
gevent                    1.4.0            py36h7b6447c_0  
glib                      2.56.2               hd408876_0  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py36h10f8cd9_2  
google-pasta              0.1.7                    pypi_0    pypi
graphite2                 1.3.13               h23475e2_0  
greenlet                  0.4.15           py36h7b6447c_0  
grpcio                    1.20.1                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.9.0            py36h7918eee_0  
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.4               hb1b8bf9_0  
heapdict                  1.0.0                    py36_2  
html5lib                  1.0.1                    py36_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      py36_0  
imageio                   2.5.0                    py36_0  
imagesize                 1.1.0                    py36_0  
importlib_metadata        0.8                      py36_0  
intel-openmp              2019.3                      199  
ipykernel                 5.1.0            py36h39e3cac_0  
ipython                   7.4.0            py36h39e3cac_0  
ipython_genutils          0.2.0            py36hb52b0d5_0  
ipywidgets                7.4.2                    py36_0  
isort                     4.3.16                   py36_0  
itsdangerous              1.1.0                    py36_0  
jbig                      2.1                  hdba287a_0  
jdcal                     1.4                      py36_0  
jedi                      0.13.3                   py36_0  
jeepney                   0.4                      py36_0  
jinja2                    2.10                     py36_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.0.1                    py36_0  
jupyter                   1.0.0                    py36_7  
jupyter_client            5.2.4                    py36_0  
jupyter_console           6.0.0                    py36_0  
jupyter_core              4.4.0                    py36_0  
jupyterlab                0.35.4           py36hf63ae98_0  
jupyterlab_server         0.2.0                    py36_0  
keras                     2.1.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
keyring                   18.0.0                   py36_0  
kiwisolver                1.0.1            py36hf484d3e_0  
krb5                      1.16.1               h173b8e3_7  
lazy-object-proxy         1.3.1            py36h14c3975_2  
libcurl                   7.64.0               h20c2e04_2  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.36               hbc83047_0  
libsodium                 1.0.16               h1bed415_0  
libssh2                   1.8.0                h1ba5d50_4  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10               h2733197_2  
libtool                   2.4.6                h7b6447c_5  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                he19cac6_0  
libxslt                   1.1.33               h7d1a2b0_0  
llvmlite                  0.28.0           py36hd408876_0  
locket                    0.2.0            py36h787c0ad_1  
lxml                      4.3.2            py36hefd8a0e_0  
lzo                       2.10                 h49e0be7_2  
markdown                  3.1                      pypi_0    pypi
markupsafe                1.1.1            py36h7b6447c_0  
matplotlib                3.0.3            py36h5429711_0  
mccabe                    0.6.1                    py36_1  
mistune                   0.8.4            py36h7b6447c_0  
mkl                       2019.3                      199  
mkl-service               1.1.2            py36he904b0f_5  
mkl_fft                   1.0.10           py36ha843d7b_0  
mkl_random                1.0.2            py36hd81dba3_0  
mock                      3.0.5                    pypi_0    pypi
more-itertools            6.0.0                    py36_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.1                hdf1c602_3  
mpmath                    1.1.0                    py36_0  
msgpack-python            0.6.1            py36hfd86e86_1  
multipledispatch          0.6.0                    py36_0  
nbconvert                 5.4.1                    py36_3  
nbformat                  4.4.0            py36h31c9010_0  
ncurses                   6.1                  he6710b0_1  
networkx                  2.2                      py36_1  
nltk                      3.4                      py36_1  
nose                      1.3.7                    py36_2  
notebook                  5.7.8                    py36_0  
numba                     0.43.1           py36h962f231_0  
numexpr                   2.6.9            py36h9e4a6bb_0  
numpy                     1.16.4                   pypi_0    pypi
numpydoc                  0.8.0                    py36_0  
olefile                   0.46                     py36_0  
openpyxl                  2.6.1                    py36_1  
openssl                   1.1.1b               h7b6447c_1  
packaging                 19.0                     py36_0  
pandas                    0.19.0                   pypi_0    pypi
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py36_1  
pango                     1.42.4               h049681c_0  
parso                     0.3.4                    py36_0  
partd                     0.3.10                   py36_1  
path.py                   11.5.0                   py36_0  
pathlib2                  2.3.3                    py36_0  
patsy                     0.5.1                    py36_0  
pcre                      8.43                 he6710b0_0  
pep8                      1.7.1                    py36_0  
pexpect                   4.6.0                    py36_0  
pickleshare               0.7.5                    py36_0  
pillow                    5.4.1            py36h34e0f95_0  
pip                       19.0.3                   py36_0  
pixman                    0.38.0               h7b6447c_0  
pluggy                    0.9.0                    py36_0  
ply                       3.11                     py36_0  
prometheus_client         0.6.0                    py36_0  
prompt_toolkit            2.0.9                    py36_0  
protobuf                  3.7.1                    pypi_0    pypi
psutil                    5.6.1            py36h7b6447c_0  
ptyprocess                0.6.0                    py36_0  
py                        1.8.0                    py36_0  
pycodestyle               2.5.0                    py36_0  
pycosat                   0.6.3            py36h14c3975_0  
pycparser                 2.19                     py36_0  
pycrypto                  2.6.1            py36h14c3975_9  
pycurl                    7.43.0.2         py36h1ba5d50_0  
pyflakes                  2.1.1                    py36_0  
pygments                  2.3.1                    py36_0  
pylint                    2.3.1                    py36_0  
pyodbc                    4.0.26           py36he6710b0_0  
pyopenssl                 19.0.0                   py36_0  
pyparsing                 2.3.1                    py36_0  
pyqt                      5.9.2            py36h05f1152_2  
pyrsistent                0.14.11          py36h7b6447c_0  
pysocks                   1.6.8                    py36_0  
pytables                  3.5.1            py36h71ec239_0  
pytest                    4.3.1                    py36_0  
pytest-arraydiff          0.3              py36h39e3cac_0  
pytest-astropy            0.5.0                    py36_0  
pytest-doctestplus        0.3.0                    py36_0  
pytest-openfiles          0.3.2                    py36_0  
pytest-remotedata         0.3.1                    py36_0  
python                    3.6.8                h0371630_0  
python-dateutil           2.8.0                    py36_0  
pytz                      2018.9                   py36_0  
pywavelets                1.0.2            py36hdd07704_0  
pyyaml                    5.1              py36h7b6447c_0  
pyzmq                     18.0.0           py36he6710b0_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 0.5.7                    py36_1  
qtconsole                 4.4.3                    py36_0  
qtpy                      1.7.0                    py36_1  
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                   py36_0  
rope                      0.12.0                   py36_0  
ruamel_yaml               0.15.46          py36h14c3975_0  
scikit-image              0.14.2           py36he6710b0_0  
scikit-learn              0.20.0                   pypi_0    pypi
scipy                     1.3.0                    pypi_0    pypi
seaborn                   0.9.0                    py36_0  
secretstorage             3.1.1                    py36_0  
send2trash                1.5.0                    py36_0  
setuptools                41.0.1                   pypi_0    pypi
simplegeneric             0.8.1                    py36_2  
singledispatch            3.4.0.3          py36h7a266c3_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.12.0                   py36_0  
snappy                    1.1.7                hbae5bb6_3  
snowballstemmer           1.2.1            py36h6febd40_0  
sortedcollections         1.1.2                    py36_0  
sortedcontainers          2.1.0                    py36_0  
soupsieve                 1.8                      py36_0  
sparse                    0.7.0                    pypi_0    pypi
sphinx                    1.8.5                    py36_0  
sphinxcontrib             1.0                      py36_1  
sphinxcontrib-websupport  1.1.0                    py36_1  
spyder                    3.3.3                    py36_0  
spyder-kernels            0.4.2                    py36_0  
sqlalchemy                1.3.1            py36h7b6447c_0  
sqlite                    3.27.2               h7b6447c_0  
statsmodels               0.9.0            py36h035aef0_0  
sympy                     1.3                      py36_0  
tblib                     1.3.2            py36h34cf8b6_0  
tensorboard               1.13.1                   pypi_0    pypi
tensorflow-estimator      1.13.0                   pypi_0    pypi
tensorflow-gpu            1.13.1                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.1                    py36_1  
testpath                  0.4.2                    py36_0  
tk                        8.6.8                hbc83047_0  
toolz                     0.9.0                    py36_0  
tornado                   6.0.2            py36h7b6447c_0  
tqdm                      4.32.2                   pypi_0    pypi
traitlets                 4.3.2            py36h674d592_0  
typed-ast                 1.3.1            py36h7b6447c_0  
unicodecsv                0.14.1           py36ha668878_0  
unixodbc                  2.3.7                h14c3975_0  
urllib3                   1.24.1                   py36_0  
wcwidth                   0.1.7            py36hdf4376a_0  
web                       0.0.1                    pypi_0    pypi
webencodings              0.5.1                    py36_1  
werkzeug                  0.14.1                   py36_0  
wheel                     0.33.1                   py36_0  
widgetsnbextension        3.4.2                    py36_0  
wrapt                     1.11.1           py36h7b6447c_0  
wurlitzer                 1.0.2                    py36_0  
xlrd                      1.2.0                    py36_0  
xlsxwriter                1.1.5                    py36_0  
xlwt                      1.3.0            py36h7b00a1f_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.3.1                he6710b0_3  
zict                      0.1.4                    py36_0  
zipp                      0.3.3                    py36_1  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0

**Comment by svjan5** [comment]
Hi,
For me the code is working, at least on Tensorflow CPU version. It seems like some datafile in missing. Please check whether `data` directory has these four files `data.txt`, `de2id.txt`, `id2freq.txt`, `voc2id.txt`.

**Comment by hjpwhu** [comment]
Thank you for your time and information.

**Comment by non-swimmer** [comment]
Hi, when I tried to run semgcn.py,  the following error occurred. It doesn't seem to be the fault of the program itself. 
Traceback (most recent call last):
  File "semgcn.py", line 606, in <module>
    model = SemGCN(args)
  File "semgcn.py", line 469, in __init__
    nn_out    = self.add_model()
  File "semgcn.py", line 364, in add_model
    adj_mat     = self.adj_mat,         w_gating   = self.p.wGate,              num_layers = self.p.gcn_layer,     name = "GCN")
  File "semgcn.py", line 279, in gcnLayer
    inp_loop = tf.tensordot(gcn_in, w_loop,  axes=[2,0])
  File "/home/yinyiping/software/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2452, in tensordot
    a_axes, b_axes = _tensordot_axes(a, axes)
  File "/home/yinyiping/software/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2440, in _tensordot_axes
    if len(a_axes) != len(b_axes):
TypeError: object of type 'int' has no len()

**Comment by svjan5** [comment]
Hi @non-swimmer,
Sure, I will look into this. Please wait for a few days.

**Comment by svjan5** [comment]
Hi @non-swimmer,
Please try the updated code. I have removed one small bug in `semgcn.py` file. It should be working now. Thanks for pointing out the error.
