### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by moore3930** [malllabiisc/WordGCN#13]
I clone the bug fixed code and run it with setting max length to 50, 70, 90, 150, **segmentation fault** comes as before. My TF version is gpu-1.12 and run it on two pieces of Tesla K80.

**Comment by loginaway** [comment]
Hi moore,

Please check the following points:
1, What is the max _sentence_ length in **your dataset** (data.txt)? This is important because the `-maxsentlen` option should be set larger than the max sentence length to avoid memory overflow. You can also eliminate some outliers (i.e. with very long sentence).
2, What is the max dependency length in your dataset? The `-maxdeplen` should be set larger than the max dependency relation length (like, if your longest dependency relation is '3|123|4 5|9|7', then set `-maxdeplen 2`)

Please check them and tell me whether it will work.

**Comment by moore3930** [comment]
Actually I used the dataset the author mentioned. So the default parameter should work.

**Comment by loginaway** [comment]
Hi,

I tried the latest code on my dataset and it turned out to be ok. I guess there is something wrong with the official dataset? 
Unfortunately my vpn failed recently, so I cannot download the updated dataset and test on it. Would you mind posting several lines of `data.txt` here?

**Comment by svjan5** [comment]
Hi,
For me, the code is working perfectly without any segmentation fault. Please make sure that you are using the right dataset ([link](https://drive.google.com/open?id=1iFpuKFpDnXCD9QpUw8wStG3ndKl7-KwX)) for training because I recently updated it as it had few redundant information. 

@loginaway, I am listing first 10 rows of `data.txt` below
```
15 14 24351 24351 10 7 436 2083 26 8385 121958 4986 215 13 6932 2293 2 1|0|26 5|1|11 5|2|23 5|3|34 5|4|7 7|6|11 5|7|9 9|8|7 7|9|38 9|10|13 13|11|2 13|12|7 10|13|16 5|14|10
25 24 90 29 272 494 15 41788 4986 3 301 131 3137 49 2135 142 66 2257 15 2293 215 13 120543 39 539 5204 2 3|0|3 3|1|21 3|2|15 6|4|2 6|5|7 3|6|16 3|7|10 12|8|0 10|9|7 12|10|11 12|11|27 3|12|17 12|13|38 15|14|15 17|15|15 17|16|2 12|17|16 17|18|13 20|19|2 18|20|16 20|21|33 20|22|19 20|23|5 3|24|10
12 11 24351 1670 1 87 8 35 20903 3 12386 6 12557 2 1|0|11 3|2|34 1|3|38 6|4|0 6|5|23 1|6|17 6|7|10 6|8|19 6|9|33 6|10|19 1|11|10
24 23 105 1905 8 1 87 10 308 3 24351 2257 24861 6641 1470 39 17396 2558 5 1 3782 4 59 664 1687 2 6|0|0 6|1|11 4|2|2 4|3|34 1|4|16 6|5|23 10|6|17 10|7|10 10|8|11 10|9|15 10|11|36 15|12|26 12|13|33 12|14|19 11|15|38 18|16|2 18|17|34 15|18|16 22|19|2 22|20|34 22|21|7 18|22|16 10|23|10
24 23 24351 527 48 1698 7 3258 570 4 6362 23 7 238 1209 79 1419 3 705 0 6 7701 15 7 2083 2 3|0|11 3|1|27 3|2|25 6|4|34 6|5|7 3|6|38 8|7|2 6|8|16 14|9|2 14|10|34 14|11|7 14|12|7 14|13|26 6|14|16 6|15|10 17|16|15 6|17|5 17|18|33 17|19|19 22|20|2 22|21|34 19|22|16 3|23|10
16 15 93 1399 6 4061 4 24351 2226 3 48 59 4 33 29 14234 4469 2 1|0|7 6|1|11 1|2|33 1|3|19 5|4|2 1|5|16 6|7|10 9|8|25 14|9|11 11|10|2 9|11|16 14|12|23 14|13|15 6|14|1 6|15|10
17 16 12473 498 4 1111 72 6135 18139 3 2190 3338 23 3416 35695 8 984 85756 2 1|0|26 5|1|11 3|2|2 1|3|16 5|4|27 5|6|15 5|7|10 5|8|36 8|9|38 12|10|2 12|11|7 8|12|16 14|13|0 8|14|17 14|15|38 5|16|10
20 19 12349 4 24351 49 272 52 1281 60 1 3582 4 508 6 40393 24351 39 500 4621 15144 2 6|0|3 2|1|2 0|2|16 6|3|27 6|4|15 6|5|21 9|7|2 9|8|34 6|9|16 14|10|2 14|11|7 11|12|33 11|13|19 9|14|16 9|15|33 18|16|7 18|17|7 9|18|19 6|19|10
27 26 1 1041 12 24351 11 10 1047 23 1 1041 12 21053 11 6 1 10588 242 50894 3 1241 2013 1667 23 1 1032 3 2105 3|0|34 3|1|26 3|2|10 6|3|3 3|4|10 6|5|21 20|6|1 11|7|2 11|8|34 11|9|26 11|10|10 6|11|16 11|12|10 11|13|33 15|14|34 11|15|19 11|16|10 11|17|5 20|18|10 20|19|11 20|21|15 24|22|2 24|23|34 20|24|16 20|25|10 20|26|17
30 29 12 21053 11 19 23 3 12 0 11 3 1264 12 42 449 6704 11 97 23 1 0 11131 0 242 19 12 27 242 11 3 2105 1|0|10 1|2|10 7|3|10 7|4|7 7|5|10 7|6|10 1|7|5 7|8|10 7|9|10 7|10|5 10|11|10 10|12|38 14|13|2 12|14|16 10|15|10 7|16|10 21|17|2 21|18|34 21|19|7 21|20|26 7|21|16 7|22|10 25|23|10 25|24|10 7|25|5 25|26|10 25|27|10 25|28|10 25|29|5
```

**Comment by loginaway** [comment]
@svjan5 Thank you, and the code runs well on the 10 rows of data on my server.

**Comment by moore3930** [comment]
Hi,

I tried to replace the data.txt with these 10 rows of data and ran the code. The same fault occurred. Could you tell me your specific running environment? I'm going to make sure everything is the same.

**Comment by moore3930** [comment]
Hi @loginaway , can I ask you some detail question on we-chat? I think we-chat communication is more convenient for us.
My we-chat number is 'Moooooooooooore'. If possible, please sent me a message. I'm looking forward to your reply.

**Comment by loginaway** [comment]
Hi moore,

Here are some information of my running environment.

Ubuntu 18.04 LTS
python 3.6.7
tensorflow              1.13.1      
tensorflow-gpu          1.8.0

**Comment by IanLiYi1996** [comment]
I also met this fault, and tried every combinations of maxsentlen and maxdeplen. It doesn't worked.

**Comment by IanLiYi1996** [comment]
Sorry for disturb you. Could you please check the code and help us to solve this problem? Thank you. If there is any improve, please let us know. Best wishes and sincerely thank you.

**Comment by loginaway** [comment]
I'm sorry that we still haven't solved the problem. And although I am willing to help you to debug the code, I can't replicate the error even when the running environment is very similar (except for the gpus). 
For now the best solution seems to be switching to another device and test whether it will work.

**Comment by svjan5** [comment]
Hi @IanLiYi1996,
The segmentation fault is only because of batch generation code which is in C++. If you are unable to resolve it because of machine architecture etc. You can try implementing the batch generation in python, it will be quite straightforward. Let me know if you need any help for that.

**Comment by IanLiYi1996** [comment]
Thank you for your answer. I will modify and debug according to your method. If there is any progress, I will inform you.

**Comment by svjan5** [comment]
Hi @IanLiYi1996,
You can also create a pull request once you have implemented it will be helpful for other users as well. 

Thanks

**Comment by Punchwes** [comment]
Hi all,

I have also met this error with the same dataset and same default setting. I found that the error begins from below line in the getBatch() method:
`wrds[cnt_wrds] = wid;
`
At this point, segmentation faulted. I am not so good at C++ but I will try to find the reason, it would be great if you could share some thought on this.

Thanks

**Comment by loginaway** [comment]
Hi @Punchwes ,
Thank you very much for the information and all the efforts you made! And thank you for sharing the solution!

**Comment by moore3930** [comment]
Hi all,

Thanks for @Punchwes, @loginaway and @svjan5   's efforts. **After modify the address obtaining code and extend the max-length param, the code finally could run on my servers.**

From the training log, it looks normally. The training speed is about 10k sentences per min (Is there some way to speed up?).

**Comment by svjan5** [comment]
Hi @moore3930,
It would be great if you create a pull request with the changes you made so that others don't face this issue in the future. 

Thanks

**Comment by svjan5** [comment]
Thanks a lot @moore3930!
Thank you everyone for their help!
