### ISSUE TITLE
how to build a syntactic graph

### ISSUE THREAD

**Issue by wizardmanxxx** [malllabiisc/WordGCN#14]
Hi,Thank you for your amazing work
However,this code doesn't seem to contain the part of how to build the syntactic graph. can i ask for sharing the code of this part? 
thank you very much.

**Comment by svjan5** [comment]
Hi @wizardmanxxx,
Thanks for your comment. 
For obtaining the syntactic graphs we used [Stanford CoreNLP Toolkit](https://stanfordnlp.github.io/CoreNLP/). We just passed each sentence to obtain its dependency parse.

regards,
