### ISSUE TITLE
"ModuleNotFoundError: No module named 'web"

### ISSUE THREAD

**Issue by guoyan1996** [malllabiisc/WordGCN#2]
Hello,there are some problem with me.
When I run "python syngcn.py -name test_embeddings -gpu 0", It has a error 
"ModuleNotFoundError: No module named 'web"
So I run "pip install web.py",
Then "ModuleNotFoundError: No module named 'web.embedding".
I wanna to know how can I use web.embedding.
Thanks.

**Comment by svjan5** [comment]
Hi, the web module is the word embedding evaluation library which I have mentioned in the readme. Just clone the repository and do python setup.py install.

**Comment by guoyan1996** [comment]
Thank you.
