### ISSUE TITLE
urllib.error.URLError

### ISSUE THREAD

**Issue by ssppff** [malllabiisc/WordGCN#21]
Hello, I am running "python syngcn.py -name test_embeddings -gpu 0 -dump "to get the URL error. I want to ask how to solve this error and how to crawl the dataset after it has been downloaded? Thank you very much for your help.

![微信图片_20191215103842](https://user-images.githubusercontent.com/48555357/70857386-277edd80-1f28-11ea-8b46-d3c842f51d54.png)

**Comment by svjan5** [comment]
Hi @ssppff,
Seems like there is some problem with your installed library or internet connection.
