### ISSUE TITLE
Hi, what can I use this model?

### ISSUE THREAD

**Issue by eyuansu62** [malllabiisc/WordGCN#23]
If I pre-train a model, how can I use to process the text? Is it same as word2vec or Glove?

**Comment by svjan5** [comment]
Yes, the model gives the embeddings similar to word2vec and GloVe.

**Comment by eyuansu62** [comment]
I got it. So if I want to use the model to encode the text to get its embeddings representation, can I directly use the embeddings.txt I trained?

Or is it similar to BERT used as an encoder? which can I fine-tuned on my tasks or using the best model you mentioned in ISSUE #16 as an encoder when I want to get the vector representation of texts?

**Comment by svjan5** [comment]
Yes, you can use 'embedding.txt'. The model is similar to word2vec, not ELMo/BERT.
