### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by guoyan1996** [malllabiisc/WordGCN#3]
Hi, when I run "python syngcn.py -name test_embeddings -gpu 0". A problem has arisen, Segmentation fault (core dumped).Have you encountered such a problem?
Thank you a lot.

**Comment by svjan5** [comment]
Hi @guoyan1996,
Please check [this issue](https://github.com/malllabiisc/WordGCN/issues/1) and let me know if it works.

**Comment by vivald99** [comment]
I have the same error: Segmentation fault (core dumped)

@svjan5 have you checked this problem?

**Comment by Zeyu-Liang** [comment]
> I have the same error: Segmentation fault (core dumped)
> 
> @svjan5 have you checked this problem?

Maybe the insufficient gpu memory.  I have the same problem on 1050TI, and it worked  with two 1080TI.

**Comment by svjan5** [comment]
Hi,
@loginaway has resolved this issue in his recent [commit](https://github.com/malllabiisc/WordGCN/pull/10). Please have a look.
