### ISSUE TITLE
How do you acquire semantic_info?

### ISSUE THREAD

**Issue by AlfredWGA** [malllabiisc/WordGCN#30]
I wonder how did you obtained lists of semantic relation pairs in the folder `semantic_info`?

**Comment by svjan5** [comment]
Hi @AlfredWGA,
We got them from these sources: 
https://github.com/mfaruqui/retrofitting
https://github.com/suhaibani/JointReps/tree/master/work

**Comment by AlfredWGA** [comment]
> Hi @AlfredWGA,
> We got them from these sources:
> https://github.com/mfaruqui/retrofitting
> https://github.com/suhaibani/JointReps/tree/master/work

Thank you for your reply!
