### ISSUE TITLE
Question about the edge direction in SemGCN

### ISSUE THREAD

**Issue by AlfredWGA** [malllabiisc/WordGCN#31]
In Figure 2 of your paper, for `hypernym` relation the edge direction is `water -> liquid`. In NLTK WordNet API, `liquid` is the `hypernym` of `water`, why the edge direction is not `water <- liquid`?

**Comment by svjan5** [comment]
We are sorry. It is just an error in the diagram.

**Comment by AlfredWGA** [comment]
> We are sorry. It is just an error in the diagram. Thanks for pointing that out.

Thank you for your reply.
