### ISSUE TITLE
How can I replace 

### ISSUE THREAD

**Issue by swyu0711** [malllabiisc/WordGCN#5]
Hi, 
To test and validate the embeddings, I need to "replace the original ~/web_data folder with the provided one", but I don't know who to replace the dataset in word-embeddings-benchmark project. The evaluation tool will automatically download datasets from google drive. 
Can you provide a more detailed instruction? 
Thank you very much!

**Comment by svjan5** [comment]
Hi @swyu0711,
Sorry for the confusion, actually when you will use web-embeddings-benchmark library, it will create a directory in your home folder with name `web_data` that folder you need to replace with the provided one. 
Let me know if you need more clarification.
