### ISSUE TITLE
No embeddings generated?

### ISSUE THREAD

**Issue by loginaway** [malllabiisc/WordGCN#8]
Hi, 

I came up with a problem while using semgcn to fine tune the given 'syngcn_embeddings.txt'. 
`sudo python3 semgcn.py -embed ./embeddings/syngcn_embeddings.txt -semantic synonyms -embed_dim 300 -name fine_tuned_embeddings -epoch 10 -gpu 0`

Everything seems going well. However, after the training finished (and it printed success message), I found nothing in the ./embeddings directory except for syngcn_embeddings.txt, which I put it there as the training set. 
In addition, the log files were output to ./log successfully, and those evaluations in them accord with the data given in the paper. 

I tried several times and it turned out the same.
Could anyone please tell me why this happened? Thanks!

**Comment by loginaway** [comment]
* typo 
I typed `sudo python3 semgcn.py -embed ./embeddings/syngcn_embeddings.txt 
                 -semantic synonyms -embed_dim 300 
                 -name fine_tuned_embeddings -epoch 10 -gpu 0`

**Comment by loginaway** [comment]
I've read semgcn.py and syngcn.py again, and now I think I know what is happening here.
There is one line
`parser.add_argument('-dump',     dest="onlyDump",       action='store_true',            help='Dump context and embed matrix')`
in the part of parsing parameters. 

So, to output the embeddings, another part is NECESSARY: '-dump' . 
Like, `sudo python3 semgcn.py -embed ./embeddings/syngcn_embeddings.txt -semantic synonyms -embed_dim 300 -name fine_tuned_embeddings -epoch 10 -gpu 0 -dump`

After I added this and ran again, the embeddings are output successfully to ./embeddings.

I guess the author forgot to put this in the instructions in README.md, would you please modify it ?: )  @svjan5

**Comment by svjan5** [comment]
Hi @loginaway,
I am sorry for the trouble. Thank you for pointing out the error. I have updated the readme.
